import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'dart:developer' as developer;

import 'package:mushpi_hub/data/models/auth_models.dart';
import 'package:mushpi_hub/data/repositories/auth_repository.dart';

/// Repository provider, now backed by Firebase Authentication instead of
/// a custom HTTP API. No baseUrl needed — Firebase project config comes
/// from firebase_options.dart (generated by `flutterfire configure`) and
/// is wired up in main.dart via Firebase.initializeApp().
final authRepositoryProvider = Provider<AuthRepository>((ref) {
  return AuthRepository();
});

enum AuthStatus { unknown, authenticating, authenticated, unauthenticated }

class AuthState {
  final AuthStatus status;
  final AuthUser? user;
  final String? errorMessage;

  const AuthState({
    required this.status,
    this.user,
    this.errorMessage,
  });

  const AuthState.unknown() : this(status: AuthStatus.unknown);
  const AuthState.unauthenticated([String? error])
      : this(status: AuthStatus.unauthenticated, errorMessage: error);
  const AuthState.authenticating() : this(status: AuthStatus.authenticating);
  const AuthState.authenticated(AuthUser user)
      : this(status: AuthStatus.authenticated, user: user);

  bool get isAuthenticated => status == AuthStatus.authenticated;
}

/// Auth state notifier. Call [bootstrap] once at app startup (e.g. from the
/// splash screen) to silently restore a session from Firebase's persisted
/// state before deciding whether to route to login or the main app.
class AuthNotifier extends StateNotifier<AuthState> {
  AuthNotifier(this._repository) : super(const AuthState.unknown());

  final AuthRepository _repository;

  /// Attempt to restore a session. Firebase persists sign-in state across
  /// app restarts automatically, so this just checks `currentUser`.
  Future<void> bootstrap() async {
    try {
      final hasSession = await _repository.hasStoredSession();
      if (!hasSession) {
        state = const AuthState.unauthenticated();
        return;
      }

      final user = await _repository.getCurrentUser();
      state = user != null
          ? AuthState.authenticated(user)
          : const AuthState.unauthenticated();
    } catch (e, stackTrace) {
      developer.log('Bootstrap failed',
          name: 'AuthNotifier', error: e, stackTrace: stackTrace);
      state = const AuthState.unauthenticated();
    }
  }

  Future<void> login({required String email, required String password}) async {
    state = const AuthState.authenticating();
    try {
      final user = await _repository.login(email: email, password: password);
      state = AuthState.authenticated(user);
    } on AuthException catch (e) {
      state = AuthState.unauthenticated(e.message);
    } catch (e) {
      state = const AuthState.unauthenticated(
          'Something went wrong. Please try again.');
    }
  }

  Future<void> signup({
    required String email,
    required String password,
    String? displayName,
  }) async {
    state = const AuthState.authenticating();
    try {
      final user = await _repository.signup(
        email: email,
        password: password,
        displayName: displayName,
      );
      state = AuthState.authenticated(user);
    } on AuthException catch (e) {
      state = AuthState.unauthenticated(e.message);
    } catch (e) {
      state = const AuthState.unauthenticated(
          'Something went wrong. Please try again.');
    }
  }

  Future<void> logout() async {
    await _repository.logout();
    state = const AuthState.unauthenticated();
  }
}

final authProvider = StateNotifierProvider<AuthNotifier, AuthState>((ref) {
  return AuthNotifier(ref.watch(authRepositoryProvider));
});
